apiVersion: v1
kind: Pod
metadata:
  name: contoh-landing-page
  labels:
    app.kubernetes.io/name: contoh-landing-page
spec:
  containers:
    - name: landing-contoh
      image: giovana02/landing-page:1
      ports: 
      - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: contoh-landing-page
spec:
  selector:
    app.kubernetes.io/name: contoh-landing-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
