apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: contoh-landing-page
  name: contoh-landing-page
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: contoh-landing-page
status:
  loadBalancer: {}
